daemon=0
server=1
listen=1

rpcuser=auruser
rpcpassword=aurpassword
rpcport=12341

rpcbind=0.0.0.0
rpcallowip=127.0.0.1
rpcallowip=192.168.0.0/16

zmqpubrawblock=tcp://0.0.0.0:28333
zmqpubhashblock=tcp://0.0.0.0:28333

addnode=aur.cryptoid.info
addnode=node1.auroracoin.is
addnode=node2.auroracoin.is

algo=sha256d