name: "Auroracoin Node"
description: "Auroracoin Full Node for Solo Mining"
version: "1.0.0"
slug: "auroracoin_node"
init: false
arch:
  - amd64
startup: application
boot: auto
host_network: true
map:
  - share:rw
image: "ghcr.io/walofz/auroracoin-addon-amd64"
options: {}
schema: {}